identifier:
  bus: 0
  vendor: 0
  product: 0
  version: 0
  uniq: "" # optional

action_mapping:
  BTN_SELECT: "channel_down"
  BTN_START: "channel_up"

midi_mappings:
  - "Default":
      # buttons
      BTN_A: 0
      BTN_B: 1
      BTN_X: 2
      BTN_Y: 3

      BTN_THUMBL: 4 # Left-analog press
      BTN_THUMBR: 5 # Right-analog press
      BTN_TL: 6 # Left bumper
      BTN_TR: 7 # Right bumper
      BTN_MODE: 8 # xbox-logo

      # analog (value needs to be a string, quotes are important)
      ABS_X: "{id: cc, cc: 0}"
      ABS_Y: "{id: pitch_bend, flip_axis: true}"
      ABS_RX: "{id: cc, cc: 1}"
      ABS_RY: "{id: cc, cc: 2, flip_axis: true}"
      ABS_Z: "{id: cc, cc: 3}"
      ABS_RZ: "{id: cc, cc: 4}"
