collision_mode = "interrupt"
exit_sequence = []

[identifier] # marking config as default as zero-value identifier
  bus = 0x00
  vendor = 0x054c
  product = 0x05c4
  version = 0x00

[defaults] # initial device state
  octave = 0
  semitone = 0
  channel = 1
  mapping = "Default"

[action_mapping]
  BTN_SELECT = "channel_down"
  BTN_START = "channel_up"
  BTN_MODE = "panic"
  BTN_TL = "cc_learning"

[deadzone]
  default = 0.1
  [deadzone.deadzones]
    ABS_X = 0.1
    ABS_Y = 0.1
    ABS_RX = 0.1
    ABS_RY = 0.1
    ABS_Z = 0.0
    ABS_RZ = 0.0
    ABS_HAT0X = 0.0
    ABS_HAT0Y = 0.0

[[mapping]]
  name = "Default"
  [mapping.keys]
    BTN_A = "0"
    BTN_B = "1"
    BTN_X = "2"
    BTN_Y = "3"
    BTN_C = "4"
    BTN_Z = "6"
    BTN_TL2 = "7"
    BTN_TR2 = "8"
    BTN_THUMBL = "9"
    BTN_THUMBR = "10"
    BTN_TL = "11"
    BTN_TR = "12"

  [mapping.analog]
    ABS_X = { type = "cc", cc = 0, deadzone_at_center = true }
    ABS_Y = { type = "pitch_bend", flip_axis = true, deadzone_at_center = true }
    ABS_RX = { type = "cc", cc = 1, cc_negative = 2, deadzone_at_center = true }
    ABS_RY = { type = "cc", cc = 3, cc_negative = 4, flip_axis = true, deadzone_at_center = true }
    ABS_Z = { type = "cc", cc = 5 }
    ABS_RZ = { type = "cc", cc = 6 }
    ABS_HAT0X = { type = "action", action = "octave_up", action_negative = "octave_down" }
    ABS_HAT0Y = { type = "action", action = "mapping_up", action_negative = "mapping_down", flip_axis = true }
