identifier:
  bus: ""
  vendor: ""
  product: ""
  version: ""
  uniq: "" # optional

action_mapping:
  KEY_ESC: "panic"

  KEY_F1: "octave_down"
  KEY_F2: "octave_up"
  KEY_F3: "semitone_down"
  KEY_F4: "semitone_up"

  KEY_F5: "mapping_down"
  KEY_F6: "mapping_up"
  KEY_F7: "channel_down"
  KEY_F8: "channel_up"

  KEY_F9: "multinote"
  KEY_F10: "channel"
  KEY_F11: "mapping"

midi_mappings:
  - "Piano":
      KEY_Z: c0
      KEY_S: c#0
      KEY_X: d0
      KEY_D: d#0
      KEY_C: e0
      KEY_V: f0
      KEY_G: f#0
      KEY_B: g0
      KEY_H: g#0
      KEY_N: a0
      KEY_J: a#0
      KEY_M: b0

      KEY_COMMA: c1
      KEY_L: c#1
      KEY_DOT: d1
      KEY_SEMICOLON: d#1
      KEY_SLASH: e1

      KEY_Q: c1
      KEY_2: c#1
      KEY_W: d1
      KEY_3: d#1
      KEY_E: e1
      KEY_R: f1
      KEY_5: f#1
      KEY_T: g1
      KEY_6: g#1
      KEY_Y: a1
      KEY_7: a#1
      KEY_U: b1

      KEY_I: c2
      KEY_9: c#2
      KEY_O: d2
      KEY_0: d#2
      KEY_P: e2
      KEY_LEFTBRACE: f2
      KEY_EQUAL: f#2
      KEY_RIGHTBRACE: g2
      KEY_BACKSPACE: g#2
      KEY_BACKSLASH: a2

  - "Chromatic":
      KEY_1: b-1
      KEY_Q: c0
      KEY_A: c#0
      KEY_Z: d0

      KEY_2: d0
      KEY_W: d#0
      KEY_S: e0
      KEY_X: f0

      KEY_3: f0
      KEY_E: f#0
      KEY_D: g0
      KEY_C: g#0

      KEY_4: g#0
      KEY_R: a0
      KEY_F: a#0
      KEY_V: b0

      KEY_5: b0
      KEY_T: c1
      KEY_G: c#1
      KEY_B: d1

      KEY_6: d1
      KEY_Y: d#1
      KEY_H: e1
      KEY_N: f1

      KEY_7: f1
      KEY_U: f#1
      KEY_J: g1
      KEY_M: g#1

      KEY_8: g#1
      KEY_I: a1
      KEY_K: a#1
      KEY_COMMA: b1

      KEY_9: b1
      KEY_O: c2
      KEY_L: c#2
      KEY_DOT: d2

      KEY_0: d2
      KEY_P: d#2
      KEY_SEMICOLON: e2
      KEY_SLASH: f2

      KEY_MINUS: f2
      KEY_LEFTBRACE: f#2
      KEY_APOSTROPHE: g2

      KEY_EQUAL: g#2
      KEY_RIGHTBRACE: a2
      KEY_ENTER: a#2

      KEY_BACKSPACE: b2
      KEY_BACKSLASH: c3

  - "Control": # unique midi events for every button

